apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-b
  template:
    metadata:
      labels:
        app: microservice-b
    spec:
      containers:
        - name: microservice-b
          image: revilllo/microservice-b:latest
          ports:
            - containerPort: 4000
          env:
            - name: DB_HOST
              value: postgres-service
            - name: DB_USER
              value: user
            - name: DB_PASS
              value: password
            - name: DB_NAME
              value: appdb
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
