services:
  mongo:
    image: mongo:4.1.13
    container_name: db
    networks:
      - net_A
    volumes:
      - mongo_data:/data/db
    ports:
      - "27019:27017"

volumes:
  mongo_data:

networks:
  net_A:
    driver: bridge
