services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    platform: linux/arm64
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    platform: linux/amd64
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      # good practice? never heard of her :3
