services:
  server:
    build: .
    container_name: express_app
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - app_net

  redis:
    image: redis:7
    container_name: redis
    networks:
      - app_net

networks:
  app_net:
