apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-custom-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: revilllo/nginx:latest
        ports:
        - containerPort: 80
