version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
    networks:
      - my_network
    volumes:
      - db_data:/var/lib/mysql

  web:
    image: node:18
    container_name: web
    working_dir: /app
    volumes:
      - ./web:/app
    command: sh -c "npm install && node index.js"
    ports:
      - "8080:3000"
    depends_on:
      - db
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  db_data:
