# .github/workflows/windows-container.yml
name: Build Windows Docker Image

on:
  push:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Windows image
        run: |
          docker build -f Dockerfile.windows -t revilllo/hello-console:windows .
          docker push revilllo/hello-console:windows
