version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - frontend_network
    volumes:
      - ./frontend:/usr/share/nginx/html

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - database
    networks:
      - frontend_network
      - backend_network
    environment:
      - DB_HOST=database
      - DB_USER=appuser
      - DB_PASSWORD=apppassword
      - DB_NAME=appdb
    ports:
      - "3000:3000"

  database:
    build: ./database
    container_name: database
    restart: always
    networks:
      - backend_network
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306" # for debugging

networks:
  frontend_network:
  backend_network:
    internal: true
